### PR TITLE
Only skip PVC creation if --namespace-mapping flag is not used

### LINKED ISSUE #410: When using --namespace-mappings, cannot restore volume if the original volume still exists
**Describe the bug**

Original namespace is the namespace in which the volume backup was created. Target namespace is the namespace I want to restore the volume to. Adding the `--namespace-mappings` allows restoring the volume in a target namespace that is different from the original namespace.

When restoring the volume, the restore operation checks if the volume already exists before creating it. The restore operation incorrectly checks if the volume exists in the original namespace. Instead, the restore operation should check if the volume exists in the target namespace where the volume is going to be created.

In the case that the volume still exists in the original namespace, the restore operation fails. In the case that the volume doesn't exist in the original namespace, the volume is correctly restored in the target namespace.

**To Reproduce**

Create original namespace:

```
$ kubectl create ns volume-test
```

Create a PVC to back up:
```
$ kubectl create --filename - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myvolume
  namespace: volume-test
spec:
  storageClassName: thin-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
EOF
```

Create a backup:

```
$ velero backup create \
    mybackup \
    --include-namespaces volume-test \
    --snapshot-volumes \
    --volume-snapshot-locations vsphere
```

Create a target namespace:

```
$ kubectl create ns volume-test-restore
```

Try to restore the backup. This will fail as the `myvolume` still exists in the `volume-test` namespace:

```
$ velero restore create \
    myrestore \
    --from-backup mybackup \
    --namespace-mappings volume-test:volume-test-restore
```

Delete the original PVC
```
$ kubectl delete -n volume-test myvolume
```

Try to restore again and it will succeed.

**Anything else you would like to add:**

The `SkipPVCCreation` method should be passed the `targetNamespace`: https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/bc2f6748a57377a1cb8b60446b2c2817daf43199/pkg/plugin/restore_pvc_action_plugin.go#L148

### PR DESCRIPTION
**Pull request by varunsrinivasan2**
**What this PR does / why we need it**:
When a Velero user uses the `--namespace-mapping` flag, PVC's should be recreated in the target namespace. Velero vSphere Plugin currently skips PVC creation if the PVC already exists in the cluster. The intended behavior of Velero restore is to recreate the PVC in the target namespace even if the PVC already exists in the cluster. This PR will check the Restore CRD and will only skip PVC creation if the user does not restore with the `--namespace-mapping` flag.

**Testing:**

**Case 1:** Logs when namespace mapping flag is used:
```
time="2024-02-22T00:12:36Z" level=info msg="Updating target PVC namespace based on the namespace mapping option in the Restore Spec" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/restore_pvc_action_plugin.go:135" pluginName=velero-plugin-for-vsphere restore=velero/finalmaptest-20240222001233
time="2024-02-22T00:12:36Z" level=info msg="Updated the target PVC namespace from nsmlog to newnsmlog based on the namespace mapping in the Restore Spec" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/restore_pvc_action_plugin.go:146" pluginName=velero-plugin-for-vsphere restore=velero/finalmaptest-20240222001233
time="2024-02-22T00:12:36Z" level=info msg="VSphere PVCRestoreItemAction for PVC newnsmlog/nginx-logs started" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/restore_pvc_action_plugin.go:150" pluginName=velero-plugin-for-vsphere restore=velero/finalmaptest-20240222001233
time="2024-02-22T00:12:36Z" level=info msg="Check if PVC newnsmlog/nginx-logs creation should be skipped" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/util/util.go:410" pluginName=velero-plugin-for-vsphere restore=velero/finalmaptest-20240222001233
time="2024-02-22T00:12:36Z" level=info msg="Creating PVC as it does not exist newnsmlog/nginx-logs" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/util/util.go:431" pluginName=velero-plugin-for-vsphere restore=velero/finalmaptest-20240222001233
```
**Case 2:** Logs when namespace mapping flag is not used and backed-up namespace & PVC are deleted:
```
time="2024-02-22T00:17:37Z" level=info msg="Updating target PVC namespace based on the namespace mapping option in the Restore Spec" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/restore_pvc_action_plugin.go:135" pluginName=velero-plugin-for-vsphere restore=velero/finalmaptest2
time="2024-02-22T00:17:37Z" level=info msg="VSphere PVCRestoreItemAction for PVC newnsmlog/nginx-logs started" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/restore_pvc_action_plugin.go:150" pluginName=velero-plugin-for-vsphere restore=velero/finalmaptest2
time="2024-02-22T00:17:37Z" level=info msg="Check if PVC newnsmlog/nginx-logs creation should be skipped" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/util/util.go:410" pluginName=velero-plugin-for-vsphere restore=velero/finalmaptest2
time="2024-02-22T00:17:37Z" level=info msg="Creating PVC as it does not exist newnsmlog/nginx-logs" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/util/util.go:431" pluginName=velero-plugin-for-vsphere restore=velero/finalmaptest2
```

**Case 3:** Logs when namespace mapping flag is not used and namespace & PVC exists in cluster:
```
time="2024-02-21T23:49:25Z" level=info msg="Updating target PVC namespace based on the namespace mapping option in the Restore Spec" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/restore_pvc_action_plugin.go:135" pluginName=velero-plugin-for-vsphere restore=velero/nodeletecase
time="2024-02-21T23:49:25Z" level=info msg="VSphere PVCRestoreItemAction for PVC nsmlog/nginx-logs started" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/restore_pvc_action_plugin.go:156" pluginName=velero-plugin-for-vsphere restore=velero/nodeletecase
time="2024-02-21T23:49:25Z" level=info msg="Check if PVC nsmlog/nginx-logs creation should be skipped" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/util/util.go:410" pluginName=velero-plugin-for-vsphere restore=velero/nodeletecase
time="2024-02-21T23:49:25Z" level=warning msg="Skipping PVC nsmlog/nginx-logs creation since it already exists." cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/util/util.go:424" pluginName=velero-plugin-for-vsphere restore=velero/nodeletecase
time="2024-02-21T23:49:25Z" level=info msg="VSphere PVCRestoreItemAction for PVC nsmlog/nginx-logs completed with err: <nil>" cmd=/plugins/velero-plugin-for-vsphere logSource="/go/src/github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/plugin/restore_pvc_action_plugin.go:158" pluginName=velero-plugin-for-vsphere restore=velero/nodeletecase
```

**Which issue(s) this PR fixes**:

Fixes #410 
https://github.com/vmware-tanzu/velero/issues/7318

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
This change will allow users to restore PVC's in the target namespace when the --namespace-mapping flag is used when creating a restore with Velero.
```

### CODE REVIEW

**Comment by xing-yang** [comment]
The change looks right.  Please add testing results and add release notes.

File: pkg/plugin/restore_pvc_action_plugin.go [hunk 1]
```diff
@@ -176,9 +177,10 @@ func (p *NewPVCRestoreItemAction) Execute(input *velero.RestoreItemActionExecute
 	bSkipPVC, err := pluginItem.SkipPVCCreation(ctx, restConfig, &pvc, p.Log)
 	if err != nil {
 		return nil, errors.WithStack(err)
-	} else if bSkipPVC {
+	} else if bSkipPVC && input.Restore.Spec.NamespaceMapping == nil {
```
Comment (deepakkinni) [inline pkg/plugin/restore_pvc_action_plugin.go:180]: Does this assume that the restore target namespace mapping does not always exist? What happens when the target ns exists, and the target PVC also exists?

From my understanding of the issue, we have a buggy `SkipPVCCreation`, in the sense that it should be checking if target ns exists, and if so target PVC within it exists. The presence of namespacemapping in the restore spec alone does not mean that it does not exist.

There is a possibility that I am wrong, if velero explicitly states that when specifying target restore namespace mapping, the target namespace should definitely not exist, in that case your fix should be sufficient.

Comment (varunsrinivasan2) [reply pkg/plugin/restore_pvc_action_plugin.go:180]: If `Restore.Spec.NamespaceMapping` is nil, that means that the `--namespace-mapping` flag was not used when creating a Restore with Velero. If the target ns exists, that means the `--namespace-mapping` flag was used when creating a Restore with Velero, therefore it will not skip PVC creation whether or not the target PVC that was backed up exists in the cluster. Checking if this spec is nil in the Restore CRD ensures PVC creation in the target namespace. 

The `--namespace-mapping` flag requires a 1-to-1 mapping of the namespace being backed up and the namespace to restore the backed up resources into (e.g. `velero restore create restore-to-new-namespace --from-backup old-namespace-backup --namespace-mappings old-ns:new-ns` where `old-ns` is the backed up namespace and `new-ns` is the target namespace)

See also: https://velero.io/docs/v1.13/restore-reference/#persistent-volume-rename
>When restoring PVs, if the PV being restored does not exist on the target cluster, Velero will create the PV using the name from the backup. Velero will rename a PV before restoring if both of the following conditions are met:

>1. The PV already exists on the target cluster.
>2. The PV’s claim namespace has been [remapped](https://velero.io/docs/v1.13/restore-reference/#restoring-into-a-different-namespace).

Comment (varunsrinivasan2) [reply pkg/plugin/restore_pvc_action_plugin.go]: Updated `SkipPVCCreation` to take `targetNamespace` as an argument.

**Review by deepakkinni — APPROVED** [review]

**Review by xing-yang — APPROVED** [review]
lgtm
